[package]
name = "json-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
file-manager = { git = "https://github.com/Tarzan9192/rust-file-manager.git", branch = "main" }
crossterm = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
